#Build phase
FROM node:16-alpine as builder

# Create a Work Directory
WORKDIR /usr/app

#Copy files to container
COPY ./package.json ./

# Download and install a dependency
RUN npm install
COPY . .
RUN npm run build

#Run phase
FROM node:16-alpine
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY --from=builder /usr/app/dist .
CMD [ "node", "server.js" ]